import type { EnhancedTableParams } from '../../../common/types';

export const ENHANCED_TABLE_DEFAULT_PARAMS: EnhancedTableParams = {
  perPage: 10,
  sort: { columnIndex: null, direction: null },
  showTotal: false,
  totalFunc: 'sum',
  totalLabel: '',
  computedColumns: [],
  showPartialRows: false,
  showMetricsAtAllLevels: false,
  computedColsPerSplitCol: false,
  stripedRows: false,
  addRowNumberColumn: false,
  hideExportLinks: false,
  hiddenColumns: '',
  showFilterBar: false,
  filterCaseSensitive: false,
  filterBarHideable: false,
  filterAsYouType: true,
  filterTermsSeparately: false,
  filterHighlightResults: false,
  filterBarWidth: '50%',
  sortSplitCols: false,
};
